import { LayerItem, MysteryBoxItem, JourneyStep, FoilTheme, VedicVerse } from '@/types';

export const QUEST_STATIONS = [
  { id: '1', title: 'Who Am I?', subtitle: '01 · DISCOVER — Know Yourself', romanNumeral: '01' },
  { id: '2', title: 'Why Is Life Special?', subtitle: '02 · CONNECT — Connect With Others', romanNumeral: '02' },
  { id: '3', title: 'What Really Makes Me Happy?', subtitle: '03 · EXPLORE — Explore Consciousness', romanNumeral: '03' },
  { id: 'final', title: 'The Sacred Mirror', subtitle: '04 · ILLUMINATE — Discover Your Inner Light', romanNumeral: '04' },
] as const;

export const IDENTITY_LAYERS: LayerItem[] = [
  {
    id: 'body',
    name: 'Body',
    iconName: 'body',
    color: '#38bdf8',
    description: 'Boyhood, youth, adulthood, old age.',
    teaching: 'The physical form is constantly changing cells, sensations, and ages, yet the conscious observer within remains unbroken.',
  },
  {
    id: 'emotions',
    name: 'Emotions',
    iconName: 'emotions',
    color: '#fb7185',
    description: 'Joy, sorrow, excitement, anxiety.',
    teaching: 'Feelings pass across consciousness like summer clouds across the sky. You are the sky, not the passing clouds.',
  },
  {
    id: 'profession',
    name: 'Profession',
    iconName: 'profession',
    color: '#fbbf24',
    description: 'Work, titles, positions, achievements.',
    teaching: 'Occupations are temporary social roles played for a brief time. Before taking this role, you still existed.',
  },
  {
    id: 'name',
    name: 'Name',
    iconName: 'name',
    color: '#a78bfa',
    description: 'The label given at physical birth.',
    teaching: 'A word assigned by others to identify the container. Before this label was given, your conscious presence was already here.',
  },
  {
    id: 'identity',
    name: 'Identity & Status',
    iconName: 'identity',
    color: '#34d399',
    description: 'Nationality, social circle, digital persona.',
    teaching: 'External mirrors reflecting perceptions. Strip away public reputation, and consciousness is still fully aware.',
  },
  {
    id: 'thoughts',
    name: 'Thoughts & Ego',
    iconName: 'thoughts',
    color: '#f472b6',
    description: 'Opinions, mental chatter, the "I" narrative.',
    teaching: 'You can quietly observe your own thoughts and watch them come and go. The observer can never be the observed.',
  },
];

export const MYSTERY_BOXES: MysteryBoxItem[] = [
  {
    id: 1,
    romanNumeral: 'Box I',
    title: 'Money & Wealth',
    tag: 'Security & Comfort',
    iconName: 'money',
    shortSummary: 'Comfort, shelter, and freedom from financial anxiety.',
    fullTeaching:
      'We spend decades securing wealth for comfort and protection. Yet no amount of wealth can purchase back a single second of expired time when life’s curtain descends.',
  },
  {
    id: 2,
    romanNumeral: 'Box II',
    title: 'Career & Status',
    tag: 'Achievement & Prestige',
    iconName: 'career',
    shortSummary: 'Honors, titles, authority, and professional standing.',
    fullTeaching:
      'We chase recognition and titles to build a towering identity. Yet every post is temporary, every badge is outgrown, and every desk is eventually passed to another.',
  },
  {
    id: 3,
    romanNumeral: 'Box III',
    title: 'Relationships',
    tag: 'Love & Belonging',
    iconName: 'relationships',
    shortSummary: 'Family bonds, deep friendships, and social companionship.',
    fullTeaching:
      'Loved ones give warmth and meaning to our days. Yet all worldly meetings are like logs drifting together on the river Yamuna, only to part as currents shift.',
  },
  {
    id: 4,
    romanNumeral: 'Box IV',
    title: 'Experiences',
    tag: 'Sensory Pleasures & Travel',
    iconName: 'experiences',
    shortSummary: 'Worldly travel, festivals, entertainment, and memories.',
    fullTeaching:
      'Sensory thrills and journeys fill our journals with vibrant color. Yet once each moment passes, the inner heart still asks: Is this truly all there is?',
  },
  {
    id: 5,
    romanNumeral: 'Box V',
    title: 'The Ultimate Inquiry',
    tag: 'The Eternal Question',
    iconName: 'purpose',
    shortSummary: 'The sacred question behind all human striving.',
    fullTeaching:
      'Beyond money, status, relationships, and worldly pleasures lies the singular gift of the human form: awakening to ask who we are and uncovering our eternal relationship with the divine.',
    isClimax: true,
  },
];

export const JOURNEY_STEPS: JourneyStep[] = [
  // CHAPTER 1: TEMPORARY HIGHS (External Highs)
  {
    id: 0,
    phase: 'rise',
    phaseLabel: 'Temporary Happiness',
    badge: 'Excitement',
    iconName: 'shopping',
    title: 'Shopping & New Things',
    quote: 'A new possession brings a brief lift to the spirit.',
    description: 'When we acquire something fresh, a momentary surge of joy elevates our mood.',
    meterValue: 65,
    boatProgressRatio: 0.12,
    bannerText: 'Acquisition · A new object brings momentary joy',
    sfx: 'chime',
  },
  {
    id: 1,
    phase: 'rise',
    phaseLabel: 'Temporary Happiness',
    badge: 'Validation',
    iconName: 'likes',
    title: 'Recognition & Attention',
    quote: 'Being seen and praised feels warm to the ego.',
    description: 'Validation, praise, and applause make us feel acknowledged and valued.',
    meterValue: 78,
    boatProgressRatio: 0.2,
    bannerText: 'Praise · Public admiration feeds external confidence',
    sfx: 'chime',
  },
  {
    id: 2,
    phase: 'rise',
    phaseLabel: 'Temporary Happiness',
    badge: 'Security',
    iconName: 'money',
    title: 'Financial Comfort',
    quote: 'Material abundance provides ease and confidence.',
    description: 'Ample resources bring temporary relief from survival stress and provide comfort.',
    meterValue: 88,
    boatProgressRatio: 0.28,
    bannerText: 'Affluence · Ease of living and material abundance',
    sfx: 'chime',
  },
  {
    id: 3,
    phase: 'rise',
    phaseLabel: 'Temporary Happiness',
    badge: 'Achievement',
    iconName: 'success',
    title: 'Success & Milestone Goals',
    quote: 'Standing at the peak of a goal feels powerful.',
    description: 'Winning the prize or securing the promotion validates our tireless work.',
    meterValue: 94,
    boatProgressRatio: 0.36,
    bannerText: 'Accomplishment · Reaching cherished earthly goals',
    sfx: 'chime',
  },
  {
    id: 4,
    phase: 'rise',
    phaseLabel: 'Temporary Happiness',
    badge: 'Deep Warmth',
    iconName: 'love',
    title: 'Affection & Relationship Joy',
    quote: 'Closeness with another brings our highest worldly peak.',
    description: 'Shared laughter, affection, and loyalty feel like the pinnacle of existence.',
    meterValue: 99,
    boatProgressRatio: 0.44,
    bannerText: 'Companionship · Shared bonds at their sweetest peak',
    sfx: 'chime',
  },

  // CHAPTER 2: LIFE TURBULENCE (The Storm)
  {
    id: 5,
    phase: 'drop',
    phaseLabel: 'Life Changes',
    badge: 'Disruption',
    iconName: 'phone',
    title: 'Loss of Daily Comfort',
    quote: 'Small instruments break, plans instantly dissolve.',
    description: 'A sudden malfunction or broken connection shatters our smooth routine.',
    meterValue: 62,
    boatProgressRatio: 0.52,
    bannerText: 'Disruption · Small fractures in daily comfort',
    sfx: 'drop',
  },
  {
    id: 6,
    phase: 'drop',
    phaseLabel: 'Life Changes',
    badge: 'Instability',
    iconName: 'job',
    title: 'Career Setback or Job Loss',
    quote: 'A position we built for years vanishes overnight.',
    description: 'Restructuring, loss of income, or fading status leaves us questioning our worth.',
    meterValue: 40,
    boatProgressRatio: 0.6,
    bannerText: 'Instability · Position and prestige slip from our hands',
    sfx: 'drop',
  },
  {
    id: 7,
    phase: 'drop',
    phaseLabel: 'Life Changes',
    badge: 'Heartache',
    iconName: 'heartbreak',
    title: 'Relationship Strain & Separation',
    quote: 'Those we depended upon can drift, change, or depart.',
    description: 'Misunderstandings or inevitable departures leave an aching hollow inside.',
    meterValue: 22,
    boatProgressRatio: 0.68,
    bannerText: 'Separation · Temporal bonds shift with changing tides',
    sfx: 'drop',
  },
  {
    id: 8,
    phase: 'drop',
    phaseLabel: 'Life Changes',
    badge: 'Vulnerability',
    iconName: 'finance',
    title: 'Sudden Financial Reversal',
    quote: 'Resources collected over years slip away like sand.',
    description: 'Sudden debts or health emergencies reveal how fragile external security is.',
    meterValue: 12,
    boatProgressRatio: 0.76,
    bannerText: 'Vulnerability · The ocean waves surge unpredictably',
    sfx: 'drop',
  },

  // CHAPTER 3: THE TURNING POINT (Pause & Reflection)
  {
    id: 9,
    phase: 'pause',
    phaseLabel: 'The Turning Point',
    badge: 'Contemplation',
    iconName: 'pause',
    title: 'The Great Observation',
    quote: 'The ocean waves rise and fall. But what about the boat?',
    description: 'Notice: circumstances will always swing like a pendulum. But who is watching the pendulum swing?',
    meterValue: 45,
    boatProgressRatio: 0.82,
    bannerText: 'Awakening · Circumstances shift, but the observer endures',
    sfx: 'calm',
  },

  // CHAPTER 4: INNER PEACE (Inner Anchor)
  {
    id: 10,
    phase: 'peace',
    phaseLabel: 'Inner Sanctuary',
    badge: 'Equanimity',
    iconName: 'peace',
    title: 'Inner Equanimity & Self-Awareness',
    quote: 'When anchored within, storms outside lose their power.',
    description: 'Realizing that worldly events happen around you, not to the eternal core of your being.',
    meterValue: 75,
    boatProgressRatio: 0.9,
    bannerText: 'Stillness · Discovering unshakeable peace within',
    sfx: 'calm',
  },

  // CHAPTER 5: SPIRITUAL CONNECTION (Eternal Refuge)
  {
    id: 11,
    phase: 'divine',
    phaseLabel: 'Spiritual Anchor',
    badge: 'Divine Refuge',
    iconName: 'spiritual',
    title: 'Eternal Connection with Krishna',
    quote: 'Rooted in divine love, the soul remains eternally unshakable.',
    description: 'Supreme happiness is not dependent on the weather of this world. It is the eternal nature of the soul reunited with God.',
    meterValue: 100,
    boatProgressRatio: 1.0,
    bannerText: 'Anchored · Eternal joy untouched by worldly turbulence',
    sfx: 'divine',
  },
];

export const FOIL_THEMES: Record<string, FoilTheme> = {
  vrindavan: {
    id: 'vrindavan',
    name: 'Ujwala Radiance',
    bgCenter: '#FAF6ED',
    bgMid: '#F5ECE0',
    bgEdge: '#EFE3D3',
    primaryGold: '#D6B15E',
    lightGold: '#E8D18A',
    darkGold: '#B8903B',
    accent: '#E8B7BE',
    textIvory: '#403A35',
    auraColor: 'rgba(214, 177, 94, 0.22)',
    borderInner: 'rgba(214, 177, 94, 0.45)',
    boxBg: 'rgba(251, 247, 239, 0.95)',
    boxBorder: 'rgba(214, 177, 94, 0.4)',
  },
  radha: {
    id: 'radha',
    name: 'Dawn Blush',
    bgCenter: '#FCF7F6',
    bgMid: '#F9ECEE',
    bgEdge: '#F2DCE0',
    primaryGold: '#D6B15E',
    lightGold: '#F3D9DC',
    darkGold: '#B8903B',
    accent: '#E8B7BE',
    textIvory: '#403A35',
    auraColor: 'rgba(232, 183, 190, 0.25)',
    borderInner: 'rgba(232, 183, 190, 0.5)',
    boxBg: 'rgba(255, 250, 250, 0.95)',
    boxBorder: 'rgba(232, 183, 190, 0.45)',
  },
  yamuna: {
    id: 'yamuna',
    name: 'Soft Lavender',
    bgCenter: '#FBF9FE',
    bgMid: '#F4EFFB',
    bgEdge: '#EAE2F5',
    primaryGold: '#D6B15E',
    lightGold: '#EEEAF5',
    darkGold: '#24566A',
    accent: '#24566A',
    textIvory: '#403A35',
    auraColor: 'rgba(221, 214, 234, 0.28)',
    borderInner: 'rgba(221, 214, 234, 0.55)',
    boxBg: 'rgba(255, 255, 255, 0.95)',
    boxBorder: 'rgba(221, 214, 234, 0.45)',
  },
};

export const VEDIC_VERSES: Record<string, VedicVerse> = {
  gita6_22: {
    id: 'gita6_22',
    kicker: 'SACRED REVELATION',
    sanskrit: 'यं लब्ध्वा चापरं लाभं मन्यते नाधिकं ततः',
    english: '"Upon gaining this spiritual connection, one considers no other gain greater, and established in such truth, one is never shaken, even in the midst of greatest difficulty."',
    citation: '— Bhagavad Gita 6.22',
    meaning: 'Supreme unshakeable joy unaffected by worldly ups and downs.',
  },
  gita2_13: {
    id: 'gita2_13',
    kicker: 'ETERNAL REALIZATION',
    sanskrit: 'देहिनोऽस्मिन्यथा देहे कौमारं यौवनं जरा',
    english: '"As the embodied soul continuously passes, in this body, from boyhood to youth to old age, the soul similarly passes into another body at death. A sober person is not bewildered by such a change."',
    citation: '— Bhagavad Gita 2.13',
    meaning: 'The conscious observer remains unchanging through all bodily transitions.',
  },
  gita2_20: {
    id: 'gita2_20',
    kicker: 'THE IMPERISHABLE SOUL',
    sanskrit: 'न जायते म्रियते वा कदाचिन्',
    english: '"For the soul there is neither birth nor death at any time. He has not come into being, does not come into being, and will not come into being. He is unborn, eternal, ever-existing, and primeval."',
    citation: '— Bhagavad Gita 2.20',
    meaning: 'The eternal essence within you is indestructible and beyond time.',
  },
  gita9_22: {
    id: 'gita9_22',
    kicker: 'DIVINE SANCTUARY',
    sanskrit: 'अनन्याश्चिन्तयन्तो मां ये जनाः पर्युपासते',
    english: '"To those who always adore Me with exclusive devotion, meditating on My transcendental form—to them I carry what they lack, and I preserve what they have."',
    citation: '— Bhagavad Gita 9.22',
    meaning: 'Anchored in unconditional divine love and spiritual refuge.',
  },
};
